replicaCount: 1

image:
  repository: springboot-crud-service
  tag: "latest"
  pullPolicy: Never

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  SPRING_PROFILES_ACTIVE: dev
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.monitoring.svc.cluster.local:4318"

autoscaling:
  enabled: false
